packages:
    - ./packages/*
    - ./tests/*
    - ./benchmarks/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: false

catalogs:
    dep:
        ts-vista: ~0.2.3
    test:
        fdir: ^6
        happy-dom: ^20
        vite-tsconfig-paths: ^6
        vitest: ^4.1

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    # config
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    # tsdown
    - "@tsdown/*"
    - "tsdown"
    # core
    - "ts-vista"
